<a href="https://colab.research.google.com/github/ramiltrinidad-ctrl/maida/blob/main/Numpy5162026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
my_arr = np.arange(10**6)
my_list = list(range(10**6))

In [9]:
print(my_arr)

[     0      1      2 ... 999997 999998 999999]


In [14]:
data = np.array([4,1,4,'3',0,8])
data

array(['4', '1', '4', '3', '0', '8'], dtype='<U21')

In [16]:
data = np.array([4,1,4,3,0,8])
data

array([4, 1, 4, 3, 0, 8])

In [17]:
data = np.array([4,1,4,3,0,8], dtype=float)
data

array([4., 1., 4., 3., 0., 8.])

In [19]:
data = np.array([4,1,4,'3',0,8], dtype=object)
data

array([4, 1, 4, '3', 0, 8], dtype=object)

In [20]:
list_data = [4,1,4,3,0,8]

In [21]:
list_data + list_data

[4, 1, 4, 3, 0, 8, 4, 1, 4, 3, 0, 8]

In [22]:
data + data

array([8, 2, 8, '33', 0, 16], dtype=object)

In [23]:
data * 3

array([12, 3, 12, '333', 0, 24], dtype=object)

In [24]:
2**86

77371252455336267181195264

In [26]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.ones(5, dtype=float)

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((5,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.full((3,4), 5.2)

array([[5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2]])

In [31]:
np.arange(10,3)

array([], dtype=int64)

In [33]:
np.linspace(1, -1, 8+1)

array([ 1.  ,  0.75,  0.5 ,  0.25,  0.  , -0.25, -0.5 , -0.75, -1.  ])

In [34]:
np.logspace(-3, 2, 4)

array([1.00000000e-03, 4.64158883e-02, 2.15443469e+00, 1.00000000e+02])

In [35]:
np.random.standard_normal(size=(3,3))

array([[-0.80933328,  0.7303738 ,  1.67547077],
       [ 0.07493268,  0.54903049, -0.62233796],
       [ 0.65097217, -0.31315572,  0.85978946]])

In [36]:
rng = np.random.default_rng(seed=1337)
rng.standard_normal((2,3))

array([[ 0.03826822,  0.47393644, -0.13774592],
       [-1.38933444,  2.52011869, -1.00639095]])

In [37]:
x1[3:]

NameError: name 'x1' is not defined

In [38]:
a = ['string', '42]']

In [39]:
a

['string', '42]']

In [40]:
b = a

In [41]:
b[0] = 'morestuff'

In [ ]:
x = np.array([])